# .graphclientrc.yml
sources:
  - name: Enlisted
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/scaffold-eth/your-contract
documents:
  - ./graphql/GetEnlisted.gql
