# .graphclientrc.yml
sources:
  - name: GetUsers
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/37762/basecamp-sepolia/version/latest
documents:
  - ./graphql/GetUsers.gql
